name: Test Katas

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  PreTestListKatas:
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.kata_tests.outputs.tests }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: List Katas
        id: kata_tests
        working-directory: src/test/java/katas/exercises
        run: |
          kata_json=$(ls *Test.java | jq -R -s -c 'split("\n")[:-1] | map(sub("Test.java$"; ""))')
          echo "Katas: $kata_json"
          echo "tests=$kata_json" >> $GITHUB_OUTPUT

  Test:
    needs: PreTestListKatas
    runs-on: ubuntu-latest
    name: ${{ matrix.kata_name }}
    strategy:
      fail-fast: false
      matrix:
        kata_name: ${{ fromJson(needs.PreTestListKatas.outputs.tests) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Unit Tests
        run: |
          echo "Testing file: ${{ matrix.kata_name }}"
          mvn -q -Dtest=${{ matrix.kata_name }}Test* test

  PostTestStoreTestId:
    needs: Test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Store Run ID
        run: |
          git config --local user.email "java@katas"
          git config --local user.name "auto-test"
          git checkout -b internal/test || git checkout internal/test
          echo ${GITHUB_RUN_ID} > .test_results_id
          git add .test_results_id && git commit -m "Update run ID"
          git push origin internal/test --force
